version: '3.8'

services:
  ranger-monitoring:
    image: ranger-monitoring:latest
    container_name: ranger-monitoring-app
    volumes:
      # Mount compiled classes
      - ./target/classes:/app/target/classes
      # Mount Ranger configuration
      - ./dont_commit_ranger_pkg/ranger-conf:/app/dont_commit_ranger_pkg/ranger-conf
      # Mount Ranger libraries
      - ./dont_commit_ranger_pkg/lib:/app/dont_commit_ranger_pkg/lib
      # Mount cache directory for Ranger policies and audit logs
      - ./dont_commit_ranger_pkg/cache:/app/cache
    # Build classpath and run MonitoringRangerPlugin
    entrypoint: ["sh", "-c"]
    command: >
      CLASSPATH="/app/target/classes:/app/dont_commit_ranger_pkg/ranger-conf";
      for jar in /app/dont_commit_ranger_pkg/lib/*.jar; do
        if [ -f "$$jar" ]; then
          CLASSPATH="$$CLASSPATH:$$jar";
        fi;
      done;
      exec java -cp "$$CLASSPATH" com.privacera.ranger.monitoring.MonitoringRangerPlugin $${MONITORING_ARGS:-"--interval 60"}
    environment:
      - MONITORING_ARGS=${MONITORING_ARGS:---interval 60}
    restart: unless-stopped

networks:
  default:
    name: ranger-monitoring-network
