version: '3.8'

services:
  ranger-monitoring:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    container_name: ranger-monitoring-app
    volumes:
      # Mount compiled classes
      - ./target/classes:/app/target/classes
      # Mount Ranger configuration
      - ./dont_commit_ranger_pkg/ranger-conf:/app/ranger-conf
      # Mount Ranger libraries
      - ./dont_commit_ranger_pkg/lib:/app/lib
      # Mount keystore directory (if you have keystore files)
      - ./dont_commit_ranger_pkg/keystore:/app/keystore
      # Mount cache directory for Ranger policies
      - ./dont_commit_ranger_pkg/cache:/app/cache
    environment:
      - JAVA_OPTS=-Dranger.service.name=hive -Dranger.service.host=localhost -Dranger.service.port=6080 -Dranger.service.user=ranger -Dranger.service.password=ranger -Dranger.policy.cache.dir=/app/cache/policycache -Dranger.temp.cache.dir=/app/cache/temp-cache -Dranger.audit.solr.urls=http://localhost:6083/solr/ranger_audits
    ports:
      - "8080:8080"
    networks:
      - ranger-network

  # Optional: Add a Ranger Admin Server for testing (if you have one)
  # ranger-admin:
  #   image: apache/ranger:latest
  #   container_name: ranger-admin
  #   ports:
  #     - "6080:6080"
  #   networks:
  #     - ranger-network

volumes:
  ranger-cache:
  ranger-temp-cache:

networks:
  ranger-network:
    driver: bridge
